const express = require('express');
const { engine } = require('express-handlebars');
const app = express();
const port = 3000;

const elements = [
  { symbol: 'H', group: 'No metal', color: 'green', row: 1, col: 1 },
  { symbol: 'He', group: 'Gas noble', color: 'blue', row: 1, col: 18 },
  { symbol: 'Li', group: 'Alcalino', color: 'purple', row: 2, col: 1 },
  { symbol: 'Be', group: 'Alcalinotérreo', color: 'yellow', row: 2, col: 2 },
  { symbol: 'B', group: 'Metaloide', color: 'orange', row: 2, col: 13 },
  { symbol: 'C', group: 'No metal', color: 'green', row: 2, col: 14 },
  { symbol: 'N', group: 'No metal', color: 'green', row: 2, col: 15 },
  { symbol: 'O', group: 'No metal', color: 'green', row: 2, col: 16 },
  { symbol: 'F', group: 'Halógeno', color: 'cyan', row: 2, col: 17 },
  { symbol: 'Ne', group: 'Gas noble', color: 'blue', row: 2, col: 18 },
  { symbol: 'Na', group: 'Alcalino', color: 'purple', row: 3, col: 1 },
  { symbol: 'Mg', group: 'Alcalinotérreo', color: 'yellow', row: 3, col: 2 },
  { symbol: 'Al', group: 'Otro metal', color: 'pink', row: 3, col: 13 },
  { symbol: 'Si', group: 'Metaloide', color: 'orange', row: 3, col: 14 },
  { symbol: 'P', group: 'No metal', color: 'green', row: 3, col: 15 },
  { symbol: 'S', group: 'No metal', color: 'green', row: 3, col: 16 },
  { symbol: 'Cl', group: 'Halógeno', color: 'cyan', row: 3, col: 17 },
  { symbol: 'Ar', group: 'Gas noble', color: 'blue', row: 3, col: 18 },
  { symbol: 'K', group: 'Alcalino', color: 'purple', row: 4, col: 1 },
  { symbol: 'Ca', group: 'Alcalinotérreo', color: 'yellow', row: 4, col: 2 },
  { symbol: 'Sc', group: 'Metales de transición', color: 'red', row: 4, col: 3 },
  { symbol: 'Ti', group: 'Metales de transición', color: 'red', row: 4, col: 4 },
  { symbol: 'V', group: 'Metales de transición', color: 'red', row: 4, col: 5 },
  { symbol: 'Cr', group: 'Metales de transición', color: 'red', row: 4, col: 6 },
  { symbol: 'Mn', group: 'Metales de transición', color: 'red', row: 4, col: 7 },
  { symbol: 'Fe', group: 'Metales de transición', color: 'red', row: 4, col: 8 },
  { symbol: 'Co', group: 'Metales de transición', color: 'red', row: 4, col: 9 },
  { symbol: 'Ni', group: 'Metales de transición', color: 'red', row: 4, col: 10 },
  { symbol: 'Cu', group: 'Metales de transición', color: 'red', row: 4, col: 11 },
  { symbol: 'Zn', group: 'Metales de transición', color: 'red', row: 4, col: 12 },
  { symbol: 'Ga', group: 'Otro metal', color: 'pink', row: 4, col: 13 },
  { symbol: 'Ge', group: 'Metaloide', color: 'orange', row: 4, col: 14 },
  { symbol: 'As', group: 'Metaloide', color: 'orange', row: 4, col: 15 },
  { symbol: 'Se', group: 'No metal', color: 'green', row: 4, col: 16 },
  { symbol: 'Br', group: 'Halógeno', color: 'cyan', row: 4, col: 17 },
  { symbol: 'Kr', group: 'Gas noble', color: 'blue', row: 4, col: 18 },
  { symbol: 'Rb', group: 'Alcalino', color: 'purple', row: 5, col: 1 },
  { symbol: 'Sr', group: 'Alcalinotérreo', color: 'yellow', row: 5, col: 2 },
  { symbol: 'Y', group: 'Metales de transición', color: 'red', row: 5, col: 3 },
  { symbol: 'Zr', group: 'Metales de transición', color: 'red', row: 5, col: 4 },
  { symbol: 'Nb', group: 'Metales de transición', color: 'red', row: 5, col: 5 },
  { symbol: 'Mo', group: 'Metales de transición', color: 'red', row: 5, col: 6 },
  { symbol: 'Tc', group: 'Metales de transición', color: 'red', row: 5, col: 7 },
  { symbol: 'Ru', group: 'Metales de transición', color: 'red', row: 5, col: 8 },
  { symbol: 'Rh', group: 'Metales de transición', color: 'red', row: 5, col: 9 },
  { symbol: 'Pd', group: 'Metales de transición', color: 'red', row: 5, col: 10 },
  { symbol: 'Ag', group: 'Metales de transición', color: 'red', row: 5, col: 11 },
  { symbol: 'Cd', group: 'Metales de transición', color: 'red', row: 5, col: 12 },
  { symbol: 'In', group: 'Otro metal', color: 'pink', row: 5, col: 13 },
  { symbol: 'Sn', group: 'Otro metal', color: 'pink', row: 5, col: 14 },
  { symbol: 'Sb', group: 'Metaloide', color: 'orange', row: 5, col: 15 },
  { symbol: 'Te', group: 'Metaloide', color: 'orange', row: 5, col: 16 },
  { symbol: 'I', group: 'Halógeno', color: 'cyan', row: 5, col: 17 },
  { symbol: 'Xe', group: 'Gas noble', color: 'blue', row: 5, col: 18 },
  { symbol: 'Cs', group: 'Alcalino', color: 'purple', row: 6, col: 1 },
  { symbol: 'Ba', group: 'Alcalinotérreo', color: 'yellow', row: 6, col: 2 },
  { symbol: 'La-Lu', group: 'Lantánidos', color: 'brown', row: 6, col: 3 },
  { symbol: 'Hf', group: 'Metales de transición', color: 'red', row: 6, col: 4 },
  { symbol: 'Ta', group: 'Metales de transición', color: 'red', row: 6, col: 5 },
  { symbol: 'W', group: 'Metales de transición', color: 'red', row: 6, col: 6 },
  { symbol: 'Re', group: 'Metales de transición', color: 'red', row: 6, col: 7 },
  { symbol: 'Os', group: 'Metales de transición', color: 'red', row: 6, col: 8 },
  { symbol: 'Ir', group: 'Metales de transición', color: 'red', row: 6, col: 9 },
  { symbol: 'Pt', group: 'Metales de transición', color: 'red', row: 6, col: 10 },
  { symbol: 'Au', group: 'Metales de transición', color: 'red', row: 6, col: 11 },
  { symbol: 'Hg', group: 'Metales de transición', color: 'red', row: 6, col: 12 },
  { symbol: 'Tl', group: 'Otro metal', color: 'pink', row: 6, col: 13 },
  { symbol: 'Pb', group: 'Otro metal', color: 'pink', row: 6, col: 14 },
  { symbol: 'Bi', group: 'Otro metal', color: 'pink', row: 6, col: 15 },
  { symbol: 'Po', group: 'Metaloide', color: 'orange', row: 6, col: 16 },
  { symbol: 'At', group: 'Halógeno', color: 'cyan', row: 6, col: 17 },
  { symbol: 'Rn', group: 'Gas noble', color: 'blue', row: 6, col: 18 },
  { symbol: 'Fr', group: 'Alcalino', color: 'purple', row: 7, col: 1 },
  { symbol: 'Ra', group: 'Alcalinotérreo', color: 'yellow', row: 7, col: 2 },
  { symbol: 'Ac-Lr', group: 'Actínidos', color: 'gray', row: 7, col: 3 },
  { symbol: 'Rf', group: 'Metales de transición', color: 'red', row: 7, col: 4 },
  { symbol: 'Db', group: 'Metales de transición', color: 'red', row: 7, col: 5 },
  { symbol: 'Sg', group: 'Metales de transición', color: 'red', row: 7, col: 6 },
  { symbol: 'Bh', group: 'Metales de transición', color: 'red', row: 7, col: 7 },
  { symbol: 'Hs', group: 'Metales de transición', color: 'red', row: 7, col: 8 },
  { symbol: 'Mt', group: 'Metales de transición', color: 'red', row: 7, col: 9 },
  { symbol: 'Ds', group: 'Metales de transición', color: 'red', row: 7, col: 10 },
  { symbol: 'Rg', group: 'Metales de transición', color: 'red', row: 7, col: 11 },
  { symbol: 'Cn', group: 'Metales de transición', color: 'red', row: 7, col: 12 },
  { symbol: 'Nh', group: 'Otro metal', color: 'pink', row: 7, col: 13 },
  { symbol: 'Fl', group: 'Otro metal', color: 'pink', row: 7, col: 14 },
  { symbol: 'Mc', group: 'Otro metal', color: 'pink', row: 7, col: 15 },
  { symbol: 'Lv', group: 'Otro metal', color: 'pink', row: 7, col: 16 },
  { symbol: 'Ts', group: 'Halógeno', color: 'cyan', row: 7, col: 17 },
  { symbol: 'Og', group: 'Gas noble', color: 'blue', row: 7, col: 18 },
  { symbol: 'La', group: 'Lantánidos', color: 'brown', row: 9, col: 4 },
  { symbol: 'Ce', group: 'Lantánidos', color: 'brown', row: 9, col: 5 },
  { symbol: 'Pr', group: 'Lantánidos', color: 'brown', row: 9, col: 6 },
  { symbol: 'Nd', group: 'Lantánidos', color: 'brown', row: 9, col: 7 },
  { symbol: 'Pm', group: 'Lantánidos', color: 'brown', row: 9, col: 8 },
  { symbol: 'Sm', group: 'Lantánidos', color: 'brown', row: 9, col: 9 },
  { symbol: 'Eu', group: 'Lantánidos', color: 'brown', row: 9, col: 10 },
  { symbol: 'Gd', group: 'Lantánidos', color: 'brown', row: 9, col: 11 },
  { symbol: 'Tb', group: 'Lantánidos', color: 'brown', row: 9, col: 12 },
  { symbol: 'Dy', group: 'Lantánidos', color: 'brown', row: 9, col: 13 },
  { symbol: 'Ho', group: 'Lantánidos', color: 'brown', row: 9, col: 14 },
  { symbol: 'Er', group: 'Lantánidos', color: 'brown', row: 9, col: 15 },
  { symbol: 'Tm', group: 'Lantánidos', color: 'brown', row: 9, col: 16 },
  { symbol: 'Yb', group: 'Lantánidos', color: 'brown', row: 9, col: 17 },
  { symbol: 'Lu', group: 'Lantánidos', color: 'brown', row: 9, col: 18 },
  { symbol: 'Ac', group: 'Actínidos', color: 'gray', row: 10, col: 4 },
  { symbol: 'Th', group: 'Actínidos', color: 'gray', row: 10, col: 5 },
  { symbol: 'Pa', group: 'Actínidos', color: 'gray', row: 10, col: 6 },
  { symbol: 'U', group: 'Actínidos', color: 'gray', row: 10, col: 7 },
  { symbol: 'Np', group: 'Actínidos', color: 'gray', row: 10, col: 8 },
  { symbol: 'Pu', group: 'Actínidos', color: 'gray', row: 10, col: 9 },
  { symbol: 'Am', group: 'Actínidos', color: 'gray', row: 10, col: 10 },
  { symbol: 'Cm', group: 'Actínidos', color: 'gray', row: 10, col: 11 },
  { symbol: 'Bk', group: 'Actínidos', color: 'gray', row: 10, col: 12 },
  { symbol: 'Cf', group: 'Actínidos', color: 'gray', row: 10, col: 13 },
  { symbol: 'Es', group: 'Actínidos', color: 'gray', row: 10, col: 14 },
  { symbol: 'Fm', group: 'Actínidos', color: 'gray', row: 10, col: 15 },
  { symbol: 'Md', group: 'Actínidos', color: 'gray', row: 10, col: 16 },
  { symbol: 'No', group: 'Actínidos', color: 'gray', row: 10, col: 17 },
  { symbol: 'Lr', group: 'Actínidos', color: 'gray', row: 10, col: 18 },
];

app.engine('handlebars', engine({
  layoutsDir: __dirname + '/views/layouts',
  defaultLayout: 'main'
}));
app.set('view engine', 'handlebars');
app.set('views', './views');

app.use(express.static('public'));

app.get('/', (req, res) => {
  res.render('home', { title: 'Tabla Periódica', elements });
});

app.listen(port, () => {
  console.log(`Servidor corriendo en http://localhost:${port}`);
});